export const USER = {
  ADD_QUESTION_TO_AUTHOR: 'ADD_QUESTION_TO_AUTHOR',
  ADD_ANSWER_TO_AUTHOR: 'ADD_ANSWER_TO_AUTHOR',
  RECEIVE_USERS: 'RECEIVE_USERS',
}

export const POLLS = {
  ADD_POLL: 'ADD_POLL',
  ADD_ANSWER_TO_POLL: 'ADD_ANSWER_TO_POLL',
  ADD_POLL_FAILED: 'ADD_POLL_FAILED',
  RECEIVE_POLLS: 'RECEIVE_POLLS'
}

export const AUTH = {
  SET_AUTHED_USER: 'SET_AUTHED_USER'
}